"""initial schema

Revision ID: 53ee1704650a
Revises: 
Create Date: 2026-05-15 22:20:40.754667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53ee1704650a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('article_no', sa.String(length=32), nullable=False),
    sa.Column('complex_name', sa.String(length=255), nullable=True),
    sa.Column('building_name', sa.String(length=255), nullable=True),
    sa.Column('trade_type', sa.String(length=8), nullable=True),
    sa.Column('trade_type_name', sa.String(length=32), nullable=True),
    sa.Column('real_estate_type', sa.String(length=16), nullable=True),
    sa.Column('real_estate_type_name', sa.String(length=32), nullable=True),
    sa.Column('deposit', sa.Integer(), nullable=True),
    sa.Column('monthly_rent', sa.Integer(), nullable=True),
    sa.Column('price_display', sa.String(length=64), nullable=True),
    sa.Column('area1_sqm', sa.Float(), nullable=True),
    sa.Column('area2_sqm', sa.Float(), nullable=True),
    sa.Column('area_pyeong', sa.Float(), nullable=True),
    sa.Column('floor_current', sa.String(length=16), nullable=True),
    sa.Column('floor_total', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('cortar_no', sa.String(length=16), nullable=True),
    sa.Column('address_text', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('cp_name', sa.String(length=128), nullable=True),
    sa.Column('cp_article_url', sa.String(length=512), nullable=True),
    sa.Column('article_status', sa.String(length=16), nullable=True),
    sa.Column('verification_type', sa.String(length=32), nullable=True),
    sa.Column('article_confirm_ymd', sa.String(length=8), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('article_no')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index('ix_articles_active_region', ['is_active', 'cortar_no', 'score'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_area_pyeong'), ['area_pyeong'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_cortar_no'), ['cortar_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_deposit'), ['deposit'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_real_estate_type'), ['real_estate_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_score'), ['score'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_trade_type'), ['trade_type'], unique=False)

    op.create_table('user_prefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('region_codes', sa.JSON(), nullable=False),
    sa.Column('trade_types', sa.JSON(), nullable=False),
    sa.Column('real_estate_types', sa.JSON(), nullable=False),
    sa.Column('deposit_min', sa.Integer(), nullable=True),
    sa.Column('deposit_max', sa.Integer(), nullable=True),
    sa.Column('monthly_rent_max', sa.Integer(), nullable=True),
    sa.Column('area_min_pyeong', sa.Float(), nullable=True),
    sa.Column('area_max_pyeong', sa.Float(), nullable=True),
    sa.Column('floor_min', sa.Integer(), nullable=True),
    sa.Column('must_have_keywords', sa.JSON(), nullable=False),
    sa.Column('exclude_keywords', sa.JSON(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_no', sa.String(length=32), nullable=False),
    sa.Column('action_type', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_no'], ['articles.article_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_no', 'action_type', name='uq_user_actions_article_action')
    )
    with op.batch_alter_table('user_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_actions_article_no'), ['article_no'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_actions_article_no'))

    op.drop_table('user_actions')
    op.drop_table('user_prefs')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_trade_type'))
        batch_op.drop_index(batch_op.f('ix_articles_score'))
        batch_op.drop_index(batch_op.f('ix_articles_real_estate_type'))
        batch_op.drop_index(batch_op.f('ix_articles_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_articles_is_active'))
        batch_op.drop_index(batch_op.f('ix_articles_deposit'))
        batch_op.drop_index(batch_op.f('ix_articles_cortar_no'))
        batch_op.drop_index(batch_op.f('ix_articles_area_pyeong'))
        batch_op.drop_index('ix_articles_active_region')

    op.drop_table('articles')
    # ### end Alembic commands ###
